projects:
  - name: Loves projekt
    environments:
      - name: Projexa-sites
        services:
          - type: web
            name: projexa-test-site
            runtime: static
            rootDir: sites/test-site
            buildCommand: "true"
            staticPublishPath: .
          - type: web
            name: projexa-test-e6fc50c2
            runtime: static
            rootDir: sites/test-e6fc50c2
            buildCommand: "true"
            staticPublishPath: .
            routes:
              - type: rewrite
                source: /*
                destination: /index.html
