const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
const menuCopy={en:['Open menu','Close menu'],es:['Abrir menú','Cerrar menú']};
let currentLanguage=localStorage.getItem('little-castle-language')||'en';

toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',menuCopy[currentLanguage][open?1:0])});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label',menuCopy[currentLanguage][0])}));
document.getElementById('year').textContent=new Date().getFullYear();

const translations={
 en:{title:'Little Castle | Restaurant & Bar',description:'Little Castle – restaurant and bar in Fuengirola. Good food, drinks and an easy-going atmosphere.',navStory:'Our story',navExperience:'The experience',navVisit:'Find us',navMaps:'Open in Maps',heroEyebrow:'RESTAURANT · BAR · FUENGIROLA',heroTitle:'A little place<br>with a <em>big</em> heart.',heroLead:'Welcome to Little Castle – an easy-going place for good food, well-mixed drinks and evenings worth lingering over.',planVisit:'Plan your visit',directions:'Get directions',scroll:'SCROLL TO DISCOVER',assistantEyebrow:'ASK LITTLE CASTLE',assistantTitle:'Your little<br><em>castle guide.</em>',assistantText:'Ask about Little Castle, visiting us, directions or the restaurant and bar experience.',promptOne:'Where is Little Castle?',promptTwo:'How do I get directions?',promptThree:'What can I find here?',chatName:'Little Castle guide',chatStatus:'Here to help',chatWelcome:'Hello! I can help with Little Castle, our Fuengirola location and how to find us. What would you like to know?',chatLabel:'Ask Little Castle a question',chatPlaceholder:'Ask about Little Castle…',chatSend:'Send <span aria-hidden="true">↑</span>',chatNote:'This guide only answers questions about Little Castle.',welcome:'WELCOME IN',storyTitle:'For those<br>simple, <em>good</em> moments.',storyOne:'Little Castle is the restaurant and bar for lunches that run longer than planned, a drink after the beach and dinners in great company.',storyTwo:'The pace is warm and the atmosphere uncomplicated. Come as you are, stay as long as you like.',explore:'Explore the atmosphere',awaits:'WHAT AWAITS',experienceTitle:'A place for<br><em>every</em> occasion.',foodNo:'01 / THE FOOD',foodTitle:'Good things on the table',foodText:'Well-made favourites for both a quick pause and a long, relaxed dinner.',barNo:'02 / THE BAR',barTitle:'Something in your glass',barText:'Settle in, order your favourite and let the evening find its own pace.',companyNo:'03 / THE COMPANY',companyTitle:'Around the same table',companyText:'Weeknight or weekend plan – what matters is who you share it with.',quote:'“Good food, cold glasses<br>and room for more <em>moments.</em>”',visitUs:'VISIT US',visitTitle:'Find<br><em>Little Castle.</em>',visitText:'You will find us in Fuengirola on the Costa del Sol. Open the map for the latest address, contact details, opening hours and directions.',viewMaps:'View on Google Maps',openMap:'Open map',seeYou:'SEE YOU SOON',closingTitle:'Make room for<br>a <em>really</em> good evening.',findCastle:'Find Little Castle',footerTagline:'Restaurant & bar · Fuengirola'},
 es:{title:'Little Castle | Restaurante y Bar',description:'Little Castle – restaurante y bar en Fuengirola. Buena comida, bebidas y un ambiente relajado.',navStory:'Nuestra historia',navExperience:'La experiencia',navVisit:'Encuéntranos',navMaps:'Abrir en Maps',heroEyebrow:'RESTAURANTE · BAR · FUENGIROLA',heroTitle:'Un lugar pequeño<br>con un corazón <em>enorme.</em>',heroLead:'Bienvenido a Little Castle: un lugar relajado para disfrutar de buena comida, bebidas bien preparadas y noches que invitan a quedarse.',planVisit:'Planifica tu visita',directions:'Cómo llegar',scroll:'DESLIZA PARA DESCUBRIR',assistantEyebrow:'PREGUNTA A LITTLE CASTLE',assistantTitle:'Tu pequeña guía<br>del <em>castillo.</em>',assistantText:'Pregunta sobre Little Castle, tu visita, cómo llegar o la experiencia del restaurante y bar.',promptOne:'¿Dónde está Little Castle?',promptTwo:'¿Cómo puedo llegar?',promptThree:'¿Qué puedo encontrar aquí?',chatName:'Guía Little Castle',chatStatus:'Aquí para ayudarte',chatWelcome:'¡Hola! Puedo ayudarte con Little Castle, nuestra ubicación en Fuengirola y cómo encontrarnos. ¿Qué te gustaría saber?',chatLabel:'Haz una pregunta a Little Castle',chatPlaceholder:'Pregunta sobre Little Castle…',chatSend:'Enviar <span aria-hidden="true">↑</span>',chatNote:'Esta guía solo responde preguntas sobre Little Castle.',welcome:'BIENVENIDO',storyTitle:'Para esos momentos<br>sencillos y <em>bonitos.</em>',storyOne:'Little Castle es el restaurante y bar para almuerzos que se alargan más de lo previsto, una copa después de la playa y cenas en buena compañía.',storyTwo:'El ritmo es cálido y el ambiente, sencillo. Ven como eres y quédate todo lo que quieras.',explore:'Descubre el ambiente',awaits:'LO QUE TE ESPERA',experienceTitle:'Un lugar para<br><em>cada</em> ocasión.',foodNo:'01 / LA COMIDA',foodTitle:'Buenas cosas en la mesa',foodText:'Favoritos bien preparados, tanto para una pausa rápida como para una cena larga y relajada.',barNo:'02 / EL BAR',barTitle:'Algo para tu copa',barText:'Ponte cómodo, pide tu favorito y deja que la noche encuentre su propio ritmo.',companyNo:'03 / LA COMPAÑÍA',companyTitle:'Alrededor de la misma mesa',companyText:'Entre semana o el fin de semana: lo importante es con quién lo compartes.',quote:'“Buena comida, copas frías<br>y espacio para más <em>momentos.</em>”',visitUs:'VISÍTANOS',visitTitle:'Encuentra<br><em>Little Castle.</em>',visitText:'Nos encontrarás en Fuengirola, en la Costa del Sol. Abre el mapa para consultar la dirección, los datos de contacto, el horario y cómo llegar.',viewMaps:'Ver en Google Maps',openMap:'Abrir mapa',seeYou:'HASTA PRONTO',closingTitle:'Haz espacio para<br>una noche <em>realmente</em> buena.',findCastle:'Encuentra Little Castle',footerTagline:'Restaurante y bar · Fuengirola'}
};
function setLanguage(language){currentLanguage=language;const copy=translations[language];document.documentElement.lang=language;document.title=copy.title;document.querySelector('meta[name="description"]').setAttribute('content',copy.description);document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=copy[el.dataset.i18n]);document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=copy[el.dataset.i18nHtml]);document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=copy[el.dataset.i18nPlaceholder]);document.querySelectorAll('.language-button').forEach(button=>{const active=button.dataset.language===language;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});toggle.setAttribute('aria-label',menuCopy[language][nav.classList.contains('open')?1:0]);localStorage.setItem('little-castle-language',language)}
document.querySelectorAll('.language-button').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.language)));
setLanguage(currentLanguage);

const chatForm=document.getElementById('chatForm');
const chatInput=document.getElementById('chatInput');
const chatMessages=document.getElementById('chatMessages');
const mapUrl='https://maps.app.goo.gl/PcJz3t2NS6W2FnXJ7';
const escapeHtml=value=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function castleReply(question){const q=question.toLowerCase();const es=currentLanguage==='es';
 if(/hello|hi\b|hola|buenas/.test(q))return es?'¡Hola! Estoy aquí para ayudarte con Little Castle en Fuengirola.':'Hello! I’m here to help with Little Castle in Fuengirola.';
 if(/where|address|location|located|donde|dónde|direcci|ubic/.test(q))return es?`Little Castle está en Fuengirola, en la Costa del Sol. <a href="${mapUrl}" target="_blank" rel="noopener">Abre Google Maps para ver la ubicación exacta ↗</a>`:`Little Castle is in Fuengirola on the Costa del Sol. <a href="${mapUrl}" target="_blank" rel="noopener">Open Google Maps for the exact location ↗</a>`;
 if(/direction|route|get there|how.*get|cómo.*lleg|llegar|ruta|indicac/.test(q))return es?`La forma más sencilla es usar Google Maps para obtener indicaciones actualizadas. <a href="${mapUrl}" target="_blank" rel="noopener">Cómo llegar a Little Castle ↗</a>`:`The easiest way is to use Google Maps for up-to-date directions. <a href="${mapUrl}" target="_blank" rel="noopener">Get directions to Little Castle ↗</a>`;
 if(/hour|open|closing|time|horario|abre|cerr/.test(q))return es?`Para consultar el horario más reciente de Little Castle, visita la ficha de Google Maps. <a href="${mapUrl}" target="_blank" rel="noopener">Ver horario actualizado ↗</a>`:`For Little Castle’s latest opening hours, please check the Google Maps listing. <a href="${mapUrl}" target="_blank" rel="noopener">View current opening hours ↗</a>`;
 if(/contact|phone|call|email|teléfono|telefono|llamar|contact/.test(q))return es?`La información de contacto más reciente está disponible en Google Maps. <a href="${mapUrl}" target="_blank" rel="noopener">Ver datos de contacto ↗</a>`:`The latest contact details are available on Google Maps. <a href="${mapUrl}" target="_blank" rel="noopener">View contact details ↗</a>`;
 if(/menu|food|eat|drink|bar|comida|comer|beber|carta|menú/.test(q))return es?'Little Castle es un restaurante y bar pensado para buena comida, bebidas bien preparadas y momentos relajados. Para la oferta actual, te recomendamos contactar directamente con el local.':'Little Castle is a restaurant and bar for good food, well-mixed drinks and easy-going moments. For the current offering, we recommend contacting the venue directly.';
 if(/book|reservation|reserve|reserv|mesa/.test(q))return es?'Para reservar o consultar disponibilidad, utiliza los datos de contacto de la ficha de Little Castle en Google Maps.':'For reservations or availability, please use the contact details on Little Castle’s Google Maps listing.';
 return es?'Puedo ayudarte con Little Castle, su ubicación en Fuengirola, cómo llegar, información de contacto, horarios y la experiencia de restaurante y bar. ¿Qué te gustaría saber?':'I can help with Little Castle, its Fuengirola location, directions, contact details, opening hours and the restaurant and bar experience. What would you like to know?';}
function addMessage(content,type){const message=document.createElement('div');message.className=`chat-message ${type}`;message.innerHTML=content;chatMessages.appendChild(message);chatMessages.scrollTop=chatMessages.scrollHeight;}
function sendQuestion(question){const text=question.trim();if(!text)return;addMessage(escapeHtml(text),'user');chatInput.value='';window.setTimeout(()=>addMessage(castleReply(text),'bot'),320);}
chatForm.addEventListener('submit',event=>{event.preventDefault();sendQuestion(chatInput.value)});
document.querySelectorAll('.assistant-prompt-list button').forEach(button=>button.addEventListener('click',()=>sendQuestion(translations[currentLanguage][button.dataset.promptKey])));
